services:
  pihkaal-me:
    build:
      context: .
      args:
        - GH_PAT
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihkaal-me.rule=Host(`pihkaal.me`)"
      - "traefik.http.routers.pihkaal-me.service=pihkaal-me"
      - "traefik.http.services.pihkaal-me.loadbalancer.server.port=80"
      - "traefik.http.routers.pihkaal-me.tls=true"
      - "traefik.http.routers.pihkaal-me.tls.certResolver=myresolver"

networks:
  web:
    external: true
